# Change these first
owner: ddt3 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Familie-dokter.net
    url: https://www.familie-dokter.net
    type: globalping
    location: netherlands
  - name: Red Grendel
    url: https://www.redgrendel.com  
    type: globalping
    location: netherlands
  - name: NextCloud
    url: https://nextcloud.familie-dokter.net
    type: globalping
    location: netherlands



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.familie-dokter.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Familie Dokter Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is my status page which uses **real-time** data from our [GitHub repository](https://github.com/ddt3/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
# Added by DDT3:
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
